=== fermyon/spin-plugins/json-schema/spin-plugin-manifest-schema-0.1.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://github.com/fermyon/spin-plugins/json-schema/spin-plugin-manifest-schema-0.1.json",
    "type": "object",
    "title": "spin-plugin-manifest-schema-0.1",
    "required": [
        "name",
        "description",
        "version",
        "spinCompatibility",
        "license",
        "packages"
    ],
    "properties": {
        "name": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "homepage": {
            "type": "string"
        },
        "version": {
            "type": "string"
        },
        "spinCompatibility": {
            "type": "string",
            "pattern": "^([><~^*]?[=]?v?(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))?(\\.(0|[1-9]\\d*))?(-(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*)?)(?:, *([><~^*]?[=]?v?(0|[1-9]\\d*)(\\.(0|[1-9]\\d*))?(\\.(0|[1-9]\\d*))?(-(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(\\.(0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\\+[0-9a-zA-Z-]+(\\.[0-9a-zA-Z-]+)*)?))*$"
        },
        "license": {
            "type": "string"
        },
        "packages": {
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "object",
                "required": [
                    "os",
                    "arch",
                    "url",
                    "sha256"
                ],
                "properties": {
                    "os": {
                        "type": "string",
                        "enum": [
                            "linux",
                            "macos",
                            "windows"
                        ]
                    },
                    "arch": {
                        "type": "string",
                        "enum": [
                            "x86",
                            "x86_64",
                            "arm",
                            "aarch64"
                        ]
                    },
                    "url": {
                        "type": "string"
                    },
                    "sha256": {
                        "type": "string"
                    }
                },
                "additionalProperties": false
            }
        }
    },
    "additionalProperties": false
}

=== fermyon/spin-plugins/manifests/example/example.json
{
    "name": "example",
    "description": "A description of the plugin.",
    "homepage": "www.example.com",
    "version": "0.2.0",
    "spinCompatibility": ">=0.4",
    "license": "Apache-2.0",
    "packages": [
        {
            "os": "linux",
            "arch": "x86_64",
            "url": "https://raw.githubusercontent.com/fermyon/spin-plugins/main/example/example.tar.gz",
            "sha256": "7827de0de5e1f5660b9685a43c8011549c1bd41dd52c458dc03ef6d33704ea16"
        },
        {
            "os": "macos",
            "arch": "aarch64",
            "url": "https://raw.githubusercontent.com/fermyon/spin-plugins/main/example/example.tar.gz",
            "sha256": "7827de0de5e1f5660b9685a43c8011549c1bd41dd52c458dc03ef6d33704ea16"
        }
    ]
}
